apiVersion: batch/v1
kind: Job
metadata:
  name: nlp-pipeline-job
spec:
  template:
    spec:
      containers:
      - name: nlp-pipeline
        image: khadijaelabbioui/nlp-ticker-classifier
        imagePullPolicy: Always 
        command: ["python", "src/main.py"]
        envFrom:
        - configMapRef:
            name: nlp-config  
        env:
        - name: CHROMA_HOST
          value: "chroma-service" 
        - name: CHROMA_PORT
          value: "8000"
        volumeMounts:
        - name: data-storage # Doit correspondre au nom dans 'volumes' ci-dessous
          mountPath: /app/artifacts
          
      # LE BLOC VOLUMES DOIT ÊTRE ALIGNÉ AVEC LE BLOC CONTAINERS
      volumes:
      - name: data-storage
        hostPath:
          path: /home/dell/Desktop/ProjectsSimplon/NLP-ticker-Classifier/artifacts
          type: DirectoryOrCreate
          
      restartPolicy: Never


      